remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "mint"
url: "https://simonharrer.github.io" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
  - jekyll-feed
locale                   : "en-US"
title                    : "Dr. Simon Harrer"
title_separator          : "-"
name                     : "Dr. Simon Harrer"
description              : "My personal homepage."
breadcrumbs              : true
words_per_minute         : 200
include: ["_pages"]
search                   : true
search_full_content      : true

twitter:
  username               : simonharrer

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single

# Site Author
author:
  name : "Dr. Simon Harrer"
  avatar           : "/simon-avatar.jpg"
  bio              : "Likes writing clean code."
  location         : "Bamberg, Germany"
#  email            : "simon.harrer@gmail.com"
  uri              :
  home             : # null (default), "absolute or relative url to link to author home"
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  # facebook         : "simonharrer"
  foursquare       :
  github           : "simonharrer"
  # gitlab           : "simon.harrer"
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         : "simonharrer" 
  pinterest        :
  soundcloud       :
  # stackoverflow    : "428536/simonh"
  steam            : # "steamId" (the last part of your profile url, e.g. https://steamcommunity.com/id/steamId/)
  tumblr           :
  twitter          : "simonharrer"
  vine             :
  weibo            :
 #  xing             : "Simon_Harrer"
  youtube          : # "https://youtube.com/c/MichaelRoseDesign"
