#!/usr/bin/env python3
"""Generate sitemap.xml, with lastmod taken from git rather than file mtime.

jekyll-sitemap derived lastmod from the file's modification time. GitHub Pages
checks the repository out fresh on every build, so every file's mtime was the
checkout time and all sixteen URLs claimed the same lastmod — telling crawlers
that articles.html, untouched since 2023, changed on every unrelated push. A
signal that fires for everything carries no information.

This reads the last commit that touched each file instead, so a page's lastmod
is the date its content actually changed.

    python3 tools/build-sitemap.py            # rewrite sitemap.xml
    python3 tools/build-sitemap.py --check    # exit 1 if the URL set is wrong
    python3 tools/build-sitemap.py --print

Note on --check: it compares the set of URLs, not the timestamps. The sitemap is
generated before the commit that contains it, so the pages changed in that same
commit only pick up their new dates on the next regeneration. Dates therefore lag
by at most one commit, which is immaterial for a crawler hint; a page missing
from the sitemap entirely is not, and that is what --check catches.
"""

import argparse
import subprocess
import sys
from pathlib import Path
from xml.sax.saxutils import escape

SITE = "https://simonharrer.com"

# 404.html is noindex and served for arbitrary URLs, so it is not a destination.
EXCLUDE = {"404.html"}

# The papers are linked from research.html and are worth finding on their own.
EXTRA_GLOBS = ["papers/*.pdf"]


def git_lastmod(path, fallback):
    """ISO date of the last commit touching this file."""
    out = subprocess.run(
        ["git", "log", "-1", "--format=%cI", "--", str(path)],
        capture_output=True, text=True, check=False,
    ).stdout.strip()
    return out or fallback


def head_date():
    return subprocess.run(
        ["git", "log", "-1", "--format=%cI"],
        capture_output=True, text=True, check=False,
    ).stdout.strip()


def entries(root):
    fallback = head_date()
    paths = sorted(p for p in root.glob("*.html") if p.name not in EXCLUDE)
    for glob in EXTRA_GLOBS:
        paths += sorted(root.glob(glob))

    out, untracked = [], []
    for p in paths:
        rel = p.relative_to(root).as_posix()
        loc = f"{SITE}/" if rel == "index.html" else f"{SITE}/{rel}"
        lastmod = git_lastmod(rel, fallback)
        if lastmod == fallback and not subprocess.run(
            ["git", "ls-files", "--error-unmatch", rel],
            capture_output=True, check=False,
        ).returncode == 0:
            untracked.append(rel)
        out.append((loc, lastmod))
    return out, untracked


def render(root):
    rows, untracked = entries(root)
    for u in untracked:
        print(f"warning: {u} is not committed; using HEAD's date", file=sys.stderr)
    body = "\n".join(
        f"  <url>\n    <loc>{escape(loc)}</loc>\n    <lastmod>{lastmod}</lastmod>\n  </url>"
        for loc, lastmod in rows
    )
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<!-- Generated by tools/build-sitemap.py. Do not edit by hand. -->\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        f"{body}\n"
        "</urlset>\n"
    )


def urls_of(text):
    import re
    return set(re.findall(r"<loc>([^<]+)</loc>", text))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the sitemap's URL set is out of date")
    ap.add_argument("--print", dest="show", action="store_true")
    args = ap.parse_args()

    root = Path(__file__).resolve().parent.parent
    payload = render(root)
    target = root / "sitemap.xml"

    if args.show:
        print(payload, end="")
        return

    if args.check:
        if not target.exists():
            print("sitemap.xml is missing", file=sys.stderr)
            raise SystemExit(1)
        want, have = urls_of(payload), urls_of(target.read_text())
        missing, extra = sorted(want - have), sorted(have - want)
        for u in missing:
            print(f"sitemap.xml is missing {u}", file=sys.stderr)
        for u in extra:
            print(f"sitemap.xml lists {u}, which no longer exists", file=sys.stderr)
        if missing or extra:
            print("run: python3 tools/build-sitemap.py", file=sys.stderr)
            raise SystemExit(1)
        print(f"sitemap.xml: {len(have)} URLs, up to date")
        return

    if target.exists() and target.read_text() == payload:
        print("sitemap.xml: unchanged")
        return
    target.write_text(payload)
    print(f"sitemap.xml: wrote {len(urls_of(payload))} URLs")


if __name__ == "__main__":
    main()
